# See https://github.com/actions/actions-runner-controller/blob/master/.github/workflows/runners.yaml
name: Build Runner Container

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
    paths:
      - 'runner/**'
      - '!runner/Makefile'
      - '.github/workflows/runners.yaml'
      - '!**.md'
  push:
    branches:
      - 'main'
    paths:
      - 'runner/**'
      - '!runner/Makefile'
      - '.github/workflows/runners.yaml'
      - '!**.md'

# https://github.com/actions/runner/pkgs/container/actions-runner
env:
  RUNNER_VERSION: '2.300.2'
  DOCKER_VERSION: '20.10.21'
  RUNNER_CONTAINER_HOOKS_VERSION: '0.1.3'
  # curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages | grep Version | awk '{print $2}'
  KUBE_VERSION: '1.25.5'


jobs:
  build-runners:
    name: Build ${{ matrix.name }}-${{ matrix.os-name }}-${{ matrix.os-version }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: actions-runner
            os-name: ubuntu
            os-version: '22.04'
            latest: 'false'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker-environment
        with:
          ghcr_username: ${{ github.actor }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Upstream Image
        uses: docker/build-push-action@v3
        with:
          context: ./runner
          file: ./runner/${{ matrix.name }}.${{ matrix.os-name }}-${{ matrix.os-version }}.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:v${{ env.RUNNER_VERSION }}-${{ matrix.os-name }}-${{ matrix.os-version }}
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:v${{ env.RUNNER_VERSION }}-${{ matrix.os-name }}-${{ matrix.os-version }}-${{ env.sha_short }}
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ matrix.os-name }}-${{ matrix.os-version }}

      - name: Build and Push OIS Image
        uses: docker/build-push-action@v3
        with:
          context: ./runner
          file: ./runner/${{ matrix.name }}-ois.${{ matrix.os-name }}-${{ matrix.os-version }}.dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          build-args: |
            KUBE_VERSION=${{ env.KUBE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.name }}-ois:v${{ env.RUNNER_VERSION }}-${{ matrix.os-name }}-${{ matrix.os-version }}
            ghcr.io/${{ github.repository }}/${{ matrix.name }}-ois:v${{ env.RUNNER_VERSION }}-${{ matrix.os-name }}-${{ matrix.os-version }}-${{ env.sha_short }}
            ghcr.io/${{ github.repository }}/${{ matrix.name }}-ois:${{ matrix.os-name }}-${{ matrix.os-version }}
